# Build configuration for the FakerOfData project
# https://github.com/derantell/FakerOfData

# Reference appveyor.yml
# http://www.appveyor.com/docs/appveyor-yml
# Appveyor build configuration
# http://www.appveyor.com/docs/build-configuration

# =============================
#  Setup
# =============================

# The version
version: 0.1.0.{build}

# Script that is run first, before repo cloning
# init:


# Script run after repo cloning, before build
install: 
  - ps: .\build\install.ps1

# Environment variables
# environment:

# =============================
#  Build
# =============================

# The target platform
# platform: AnyCPU

# Build configuration 
configuration: Release

# Restore nuget packages in solution
before_build: 
  - nuget restore

build:
  publish_nuget: true # Publish nuget artifacts to project feed


# =============================
#  Test	
# =============================

# Test assemblies are discovered automatically

# =============================
# Notifications
# =============================

# Send notification to slack, Team Derantell, channel fakerofdata
notifications:
  - provider: Slack
    auth_token:
      secure: IHzjlkkNTOraw1kom7wqVo7fXqQH1BwELc4om4CjiBrB7rgEfeEuAjoHshxe8EiL
    channel: fakerofdata
